FROM golang:alpine

WORKDIR /app

RUN apk add --update --no-cache git

ARG MONGO_DB_URI
ENV MONGO_DB_URI=${MONGO_DB_URI}

ARG MONGO_USER_CERT_PATH
RUN echo "$MONGO_USER_CERT_PATH" > user_cert.pem

ENV MONGO_USER_CERT_PATH="./user_cert.pem"

ARG AUTH0_ENABLED
ENV AUTH0_ENABLED=${AUTH0_ENABLED}

ARG AUTH0_DOMAIN
ENV AUTH0_DOMAIN=${AUTH0_DOMAIN}

ARG AUTH0_CLIENT_ID
ENV AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}

ARG AUTH0_CLIENT_SECRET
ENV AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}

ARG AUTH0_CALLBACK_URL
ENV AUTH0_CALLBACK_URL=${AUTH0_CALLBACK_URL}

ARG SESSION_SECRET
ENV SESSION_SECRET=${SESSION_SECRET}

ADD . .

RUN go build -o ./run ./cmd

ENTRYPOINT [ "./run" ]
