name: pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        permissions: 'write-all'
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Authenticate with Google Cloud
              id: auth
              uses: google-github-actions/auth@v0.4.0
              with:
                workload_identity_provider: 'projects/495615477282/locations/global/workloadIdentityPools/mosq-center-id-pool/providers/mosq-center-pool-provider'
                service_account: 'pipeline@mosq-center.iam.gserviceaccount.com'
            - name: Bump version and push tag
              id: tag_version
              uses: mathieudutour/github-tag-action@v6.1
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                tag_prefix: 'v'
                append_to_pre_release_tag: 'rc'
                release_branches: 'main'
            - name: Build and Publish Docker Image
              id: build_docker_image
              uses: docker/build-push-action@v2
              with:
                context: .
                file: ./Dockerfile
                push: true
                tags: ${{ steps.tag_version.outputs.new_tag }}
