name: pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
    GOOGLE_ARTIFACT_REGISTRY: europe-west1-docker.pkg.dev
jobs:
    build:
        runs-on: ubuntu-latest
        permissions: 'write-all'
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Authenticate with Google Cloud
              id: auth
              uses: google-github-actions/auth@v0.4.0
              with:
                workload_identity_provider: 'projects/495615477282/locations/global/workloadIdentityPools/mosq-center-id-pool/providers/mosq-center-pool-provider'
                service_account: 'pipeline@mosq-center.iam.gserviceaccount.com'
            - name: Create artifact path output
              id: output_artifact
              run: echo '::set-output name=artifact_path::${{ env.GOOGLE_ARTIFACT_REGISTRY }}/mosq-center/mosq-center-docker/mosq-center'
            - name: Extract metadata (tags, labels) for Google Docker
              id: meta
              uses: docker/metadata-action@v5
              with:
                images: ${{ steps.output_artifact.outputs.artifact_path }}
            - name: Build and Publish Docker Image
              id: build_docker_image
              uses: docker/build-push-action@v2
              with:
                context: .
                file: ./Dockerfile
                push: true
                tags: ${{ steps.meta.outputs.tags }}
